---
name: Build preview slides for PRs
on:
  pull_request:
    branches: 
      - dev
jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Install marp
        run: npm install -g @marp-team/marp-cli@1.4.0

      - name: Build HTML slides
        run: marp README.md

      - name: Build PDF slides
        run: marp README.md --pdf --allow-local-files

      - name: Upload slides
        uses: actions/upload-artifact@v2
        with:
          name: slides-preview-${{ env.BRANCH_NAME }}
          path: |
            README.html
            README.pdf
